### PR TITLE
updates the text in the Add Image activity

### PR DESCRIPTION
**Pull request by lmkeston**
updates the text as described here: https://github.com/githubtraining/intro-to-html/issues/29

### CODE REVIEW

**Comment by amyschoen** [comment]
This is a duplicate of #35.  I used the text that @crichID suggested when I did a new PR after deleting my fork too early.

**Comment by lmkeston** [comment]
> 
> 
> This is a duplicate of #35. I used the text that @crichID suggested when I did a new PR after deleting my fork too early.

Thanks @amyschoen. I'll close this one and merge yours.

**Comment by amyschoen** [comment]
Awesome.  Thank you @lmkeston.  Sorry to make you do extra work by deleting my fork too early.

**Comment by lmkeston** [comment]
@amyschoen no problem at all!

**Pull request closed without merging**
